# Form implementation generated from reading ui file 'c:\Users\ZZQ\Desktop\ui_demo\untitled.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(934, 616)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(parent=Form)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parent=self.widget_2)
        self.widget.setMaximumSize(QtCore.QSize(80, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setStyleSheet("QPushButton {    \n"
"    background-image: url(:/background/文档.png);  /* 设置背景图像 */\n"
"    background-position: left center;  /* 背景图像居中 */\n"
"    background-repeat: no-repeat;  /* 不重复背景图像 */\n"
"    border: none;  /* 去除按钮边框 */\n"
"    border-left: 22px solid transparent;\n"
"    background-color: rgb(37, 41, 48);  /* 设置背景色 */\n"
"    text-align: left;  /* 文字左对齐 */\n"
"    padding: 50px;\n"
"\n"
"    color: rgb(113, 126, 149);  /* 设置文字颜色 */\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(89, 47, 49);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(189, 147, 249);\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_2.setStyleSheet("QPushButton {    \n"
"    background-image: url(:/background/文档.png);  /* 设置背景图像 */\n"
"    background-position: center;  /* 背景图像居中 */\n"
"    background-repeat: no-repeat;  /* 不重复背景图像 */\n"
"    border: none;  /* 去除按钮边框 */\n"
"    border-left: solid transparent;  /* 左边框透明，占位 */\n"
"    background-color: rgb(37, 41, 48);  /* 设置背景色 */\n"
"    text-align: left;  /* 文字左对齐 */\n"
"    padding: 50px;\n"
"\n"
"    color: rgb(113, 126, 149);  /* 设置文字颜色 */\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(89, 47, 49);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(189, 147, 249);\n"
"}\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_3.setStyleSheet("QPushButton {    \n"
"    background-image: url(:/background/文档.png);  /* 设置背景图像 */\n"
"    background-position: center;  /* 背景图像居中 */\n"
"    background-repeat: no-repeat;  /* 不重复背景图像 */\n"
"    border: none;  /* 去除按钮边框 */\n"
"    border-left: solid transparent;  /* 左边框透明，占位 */\n"
"    background-color: rgb(37, 41, 48);  /* 设置背景色 */\n"
"    text-align: left;  /* 文字左对齐 */\n"
"    padding: 50px;\n"
"\n"
"    color: rgb(113, 126, 149);  /* 设置文字颜色 */\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(89, 47, 49);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(189, 147, 249);\n"
"}\n"
"\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_4.setMouseTracking(True)
        self.pushButton_4.setStyleSheet("QPushButton {    \n"
"    background-image: url(:/background/文档.png);  /* 设置背景图像 */\n"
"    background-position: center;  /* 背景图像居中 */\n"
"    background-repeat: no-repeat;  /* 不重复背景图像 */\n"
"    border: none;  /* 去除按钮边框 */\n"
"    border-left: solid transparent;  /* 左边框透明，占位 */\n"
"    background-color: rgb(37, 41, 48);  /* 设置背景色 */\n"
"    text-align: left;  /* 文字左对齐 */\n"
"    padding: 50px;\n"
"\n"
"    color: rgb(113, 126, 149);  /* 设置文字颜色 */\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(89, 47, 49);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(189, 147, 249);\n"
"}\n"
"\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_5.setStyleSheet("QPushButton {    \n"
"    background-image: url(:/background/文档.png);  /* 设置背景图像 */\n"
"    background-position: center;  /* 背景图像居中 */\n"
"    background-repeat: no-repeat;  /* 不重复背景图像 */\n"
"    border: none;  /* 去除按钮边框 */\n"
"    border-left: solid transparent;  /* 左边框透明，占位 */\n"
"    background-color: rgb(37, 41, 48);  /* 设置背景色 */\n"
"    text-align: left;  /* 文字左对齐 */\n"
"    padding: 50px;\n"
"\n"
"    color: rgb(113, 126, 149);  /* 设置文字颜色 */\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(89, 47, 49);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(189, 147, 249);\n"
"}\n"
"\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.horizontalLayout.addWidget(self.widget)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.widget_2)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.page)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_3.addWidget(self.textBrowser)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textBrowser_2 = QtWidgets.QTextBrowser(parent=self.page_2)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout_4.addWidget(self.textBrowser_2)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.widget_2)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.pushButton_2.setText(_translate("Form", "PushButton"))
        self.pushButton_3.setText(_translate("Form", "PushButton"))
        self.pushButton_4.setText(_translate("Form", "PushButton"))
        self.pushButton_5.setText(_translate("Form", "PushButton"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">第一个</p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">第二个</p></body></html>"))
